version: '3.3'

services:
  wordpress:
    build: .
    restart: always
    ports:
      - 8080:80
    env_file: .env
    volumes:
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    env_file: .env
    volumes:
      - db:/var/lib/mysql

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8888:8080

networks:
  back:

volumes:
  db:
